modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU GPLv3"
[[mods]]
modId = "fancyenchantments"
version = "1.1.1"
displayName = "Fancy Enchantments"
logoFile = "fe.png"
credits = "FOOLSIX"
authors = "FOOLSIX"
description = "This mod adds some intersting and powerful enchantments to Minecraft.\n\nWIP."
[[dependencies.fancyenchantments]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fancyenchantments]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fancyenchantments]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.3.0,)"
side = "CLIENT"